### ISSUE TITLE
Lambdas and lambdas part 2 (Learn, polish language)

### ISSUE THREAD

**Issue by SzopuCpp** [PoetaKodu/CppLangNet#64]
**Part I:**
- [x] Definition
- [ ] std::count_if()
- [x] std::transform()

Part II:
- [ ] std::function
- [ ] std::for_each()
- [ ] keyword "mutable" in lambdas declaration
- [ ] throw exceptions from lambdas
